# @package _global_
rdd:
  rdd_model_class_path: src.rdd.rdd_models.SingleLinearRddModel
  rdd_model_kwargs:
    kernel_bandwidth: 5
    kernel_shape: rectangular
  treatment_column: treatment
  outcome_column: diastolic blood pressure
  time_step_column: hours_in
  time_series_unique_id_columns:
    - subject_id
  destination_file_path: /Users/yacine/Desktop/tmp/mimic_rdd_dataset_repro.parquet
  static_columns_to_add: []
  seeds: []
  n_jobs: 8
